import type { LucideIcon } from 'lucide-react'
import {
  LayoutDashboard,
  Building2,
  MapPin,
  GraduationCap,
  Users,
  ScanLine,
  Wallet,
  QrCode,
  Clock3,
  CalendarCheck,
  ListTree,
  BarChart3,
  Settings,
  UserCircle,
  Bell,
  UserCheck,
  AreaChart,
  Calendar,
  CalendarCheck2,
  UserCog,
} from 'lucide-react'
import type { Page, Role } from '../types'

export const pageAccess: Record<Role, Page[]> = {
  AUTHORITY: [
    'overview',
    'companies',
    'userManagement',
    'teacherMonitoring',
    'studentMonitoring',
    'paymentManagement',
    'examSites',
    'qrLogs',
    'reportsAnalytics',
    'directory',
    'settings',
    'profile',
  ],
  COMPANY: [
    'companyOverview',
    'companyTeachers',
    'companyStudents',
    'companyStudentManagement',
    'companyPayments',
    'companyExamSchedule',
    'companyReports',
    'profile',
  ],
  TEACHER: ['teacherStudents', 'teacherTimetable', 'teacherExams', 'teacherPayments', 'profile'],
  STUDENT: [
    'studentDashboard',
    'studentPayment',
    'studentQrTicket',
    'studentTimetable',
    'studentExamDetails',
    'studentNotifications',
    'profile',
  ],
  EXAM_OFFICER: [
    'officerDashboard',
    'officerQrScanner',
    'officerVerification',
    'officerAttendance',
    'officerReports',
    'profile',
  ],
}

export const pageLabels: Record<Page, string> = {
  overview: 'Dashboard',
  companies: 'Company Management',
  userManagement: 'User Management',
  directory: 'Directory',
  examSites: 'Examination Management',
  teacherMonitoring: 'Teacher Monitoring',
  studentMonitoring: 'Student Monitoring',
  paymentManagement: 'Payment Management',
  qrLogs: 'QR Verification Logs',
  reportsAnalytics: 'Reports & Analytics',
  settings: 'Settings',
  companyOverview: 'Overview',
  companyTeachers: 'Teacher Management',
  companyStudents: 'Student Approval',
  companyStudentManagement: 'Students',
  companyPayments: 'Payments',
  companyExamSchedule: 'Examination Schedule',
  companyReports: 'Reports',
  teacherStudents: 'My Students',
  teacherTimetable: 'Timetable',
  teacherExams: 'Examination Schedule',
  teacherPayments: 'Payment Status',
  studentDashboard: 'Dashboard',
  studentPayment: 'Make payment',
  studentQrTicket: 'My QR ticket',
  studentTimetable: 'My timetable',
  studentExamDetails: 'Examination Details',
  studentNotifications: 'Notifications',
  officerDashboard: 'Dashboard',
  officerQrScanner: 'QR Scanner',
  officerVerification: 'Student Verification',
  officerAttendance: 'Attendance',
  officerReports: 'Reports',
  profile: 'Profile',
}

export const pageIcons: Record<Page, LucideIcon> = {
  overview: LayoutDashboard,
  companies: Building2,
  userManagement: UserCog,
  directory: ListTree,
  examSites: MapPin,
  teacherMonitoring: GraduationCap,
  studentMonitoring: Users,
  paymentManagement: Wallet,
  qrLogs: ScanLine,
  reportsAnalytics: BarChart3,
  settings: Settings,
  companyOverview: LayoutDashboard,
  companyTeachers: GraduationCap,
  companyStudents: Users,
  companyStudentManagement: ListTree,
  companyPayments: Wallet,
  companyExamSchedule: CalendarCheck,
  companyReports: BarChart3,
  teacherStudents: Users,
  teacherTimetable: Clock3,
  teacherExams: CalendarCheck,
  teacherPayments: Wallet,
  studentDashboard: LayoutDashboard,
  studentPayment: AreaChart,
  studentQrTicket: QrCode,
  studentTimetable: Calendar,
  studentExamDetails: CalendarCheck,
  studentNotifications: Bell,
  officerDashboard: LayoutDashboard,
  officerQrScanner: ScanLine,
  officerVerification: UserCheck,
  officerAttendance: CalendarCheck2,
  officerReports: BarChart3,
  profile: UserCircle,
}
